/*
 * export.js -- PDF and CSV output.
 *
 * The layouts are ports of the iOS PDFExporter: US Letter, 36pt margins, a
 * title band over a rule, label/value rows with the value right-aligned, and a
 * paginated table for the full history. Keeping them identical means a PDF
 * from the phone and one from the web can sit in the same compliance folder
 * without looking like they came from different tools.
 *
 * Two details carried over deliberately:
 *   - Coordinates print at 4 decimal places (~11 m) with the accuracy always
 *     shown. Six decimals implied ~11 cm of precision the fix does not have.
 *   - A photo that will not fit on the remaining page starts a fresh one rather
 *     than being clipped, and is never upscaled past its natural size.
 */
(function (root) {
  "use strict";
  const FR = (root.FloRun = root.FloRun || {});

  const PAGE = FR.pdf.LETTER;
  const MARGIN = 36;
  const CONTENT_WIDTH = PAGE.width - MARGIN * 2;
  const CONTENT_RIGHT = PAGE.width - MARGIN;
  const BOTTOM_LIMIT = PAGE.height - MARGIN - 36;   // leaves room for the footer

  const GRAY = [0.35, 0.35, 0.35];
  const LIGHT = [0.55, 0.55, 0.55];
  const RULE = [0.8, 0.8, 0.8];
  const STRIPE = [0.97, 0.97, 0.97];
  const HEADER_FILL = [0.9, 0.9, 0.9];

  const APP_VERSION = "1.0";

  function versionLine() {
    return "Generated by FloRun " + APP_VERSION + " (web) · " +
      FR.format.formatTimestampMedium(new Date());
  }

  /* ── shared pieces ─────────────────────────────────────────────────── */

  function drawHeader(doc, title, subtitle, y) {
    doc.text(title, MARGIN, y, { size: 22, bold: true });
    doc.text(subtitle, MARGIN, y + 30, { size: 11, color: GRAY });
    return y + 50;
  }

  function drawRule(doc, y) {
    doc.line(MARGIN, y, CONTENT_RIGHT, y, { width: 0.5, color: RULE });
    return y + 1;
  }

  function drawSectionTitle(doc, text, y) {
    doc.text(text, MARGIN, y, { size: 13, bold: true });
    return y + 22;
  }

  function drawKV(doc, key, value, y, opts) {
    const o = opts || {};
    const size = o.valueSize || 12;
    const lineHeight = Math.max(size + 4, 16);
    const keyWidth = 220;
    doc.text(key, MARGIN, y + (lineHeight - 13) / 2, { size: 11, color: GRAY });
    doc.text(value, MARGIN + keyWidth, y, {
      size: size, bold: !!o.bold, align: "right", width: CONTENT_WIDTH - keyWidth,
    });
    return y + lineHeight + 2;
  }

  function drawWrappedKV(doc, key, value, y) {
    doc.text(key, MARGIN, y, { size: 11, color: GRAY });
    const used = doc.textBlock(value, MARGIN, y + 14, CONTENT_WIDTH, { size: 11, italic: true });
    return y + 14 + used + 6;
  }

  function drawFooter(doc) {
    doc.text(versionLine(), MARGIN, PAGE.height - MARGIN - 12, {
      size: 9, color: LIGHT, align: "center", width: CONTENT_WIDTH,
    });
  }

  function locationValue(rec) {
    const coord = rec.latitude.toFixed(4) + ", " + rec.longitude.toFixed(4);
    if (rec.locationAccuracyMeters != null && isFinite(rec.locationAccuracyMeters) &&
        rec.locationAccuracyMeters > 0) {
      return coord + "  ±" + Math.round(rec.locationAccuracyMeters) + " m";
    }
    return coord + "  (accuracy unspecified)";
  }

  /* ── single measurement ────────────────────────────────────────────── */

  /*
   * `photoBytes` is optional; when present it must be baseline JPEG bytes.
   * Resolved by the caller so this stays synchronous and testable.
   */
  function buildSinglePDF(rec, photoBytes) {
    const core = FR.core, fmt = FR.format;
    const doc = FR.pdf.createDocument();
    doc.addPage();

    let y = MARGIN;
    y = drawHeader(doc, "FloRun Flow Measurement", fmt.formatTimestampMedium(rec.timestamp), y);
    y = drawRule(doc, y) + 12;

    y = drawSectionTitle(doc, "Measurement", y);
    y = drawKV(doc, "Recorded", fmt.formatTimestampMedium(rec.timestamp), y);

    if (rec.mode === core.MODES.weir.id) {
      const type = FR.weir.typeFor(rec.weirType);
      y = drawKV(doc, "Method", "V-notch weir", y);
      y = drawKV(doc, "Notch Geometry", type.displayName, y);
      y = drawKV(doc, "Head Height", fmt.formatVolume(rec.headInches) + " in", y);
    } else if (rec.mode === core.MODES.manualEntry.id) {
      y = drawKV(doc, "Method", "Manual flow rate entry", y);
    } else {
      const unit = core.unitFor(rec.volumeUnit);
      y = drawKV(doc, "Method", "Timed volume", y);
      y = drawKV(doc, "Elapsed Time", fmt.formatElapsed(rec.elapsedSeconds), y);
      y = drawKV(doc, unit.isDirectVolume ? "Volume Captured" : "Water Column Height",
        fmt.formatVolume(rec.volume) + " " + unit.inputSuffix, y);
      if (!unit.isDirectVolume) {
        y = drawKV(doc, "Bucket Type", unit.displayName, y);
      }
      y = drawKV(doc, "Volume in US Gallons",
        fmt.formatGallons(core.recordVolumeInUSGallons(rec)), y);
    }

    y += 10;
    y = drawSectionTitle(doc, "Flow Rates (US gal)", y);
    y = drawKV(doc, "Gallons Per Minute (GPM)", fmt.formatFlow(rec.gpm), y, { bold: true, valueSize: 14 });
    y = drawKV(doc, "Gallons Per Hour (GPH)", fmt.formatFlow(rec.gph), y, { bold: true, valueSize: 14 });
    y = drawKV(doc, "Gallons Per Day (GPD)", fmt.formatFlow(rec.gpd), y, { bold: true, valueSize: 14 });

    const hasSite = !!(rec.siteLabel && rec.siteLabel.length);
    const hasNotes = !!(rec.notes && rec.notes.length);
    if (hasSite || hasNotes || core.recordHasLocation(rec)) {
      y += 10;
      y = drawSectionTitle(doc, "Site & Notes", y);
      if (hasSite) y = drawKV(doc, "Site Label", rec.siteLabel, y);
      if (core.recordHasLocation(rec)) y = drawKV(doc, "Location", locationValue(rec), y);
      if (hasNotes) y = drawWrappedKV(doc, "Notes", rec.notes, y);
    }

    if (photoBytes && photoBytes.length) {
      y = drawPhoto(doc, photoBytes, y);
    }

    drawFooter(doc);
    return doc.build();
  }

  function drawPhoto(doc, bytes, y) {
    const info = FR.pdf.parseJPEG(bytes);
    if (!info) return y;

    // Never upscale: a small or cropped photo stays at its natural size.
    const scale = Math.min(1, CONTENT_WIDTH / info.width);
    const drawW = info.width * scale;
    const drawH = info.height * scale;

    let cursor = y + 10;
    // Start a fresh page rather than clipping the photo at the page break.
    if (cursor + 22 + drawH > BOTTOM_LIMIT) {
      drawFooter(doc);
      doc.addPage();
      cursor = MARGIN;
    }
    cursor = drawSectionTitle(doc, "Photo", cursor);

    const available = BOTTOM_LIMIT - cursor;
    const finalH = Math.min(drawH, available);
    const finalW = drawH > 0 ? finalH * (drawW / drawH) : drawW;
    const x = MARGIN + (CONTENT_WIDTH - finalW) / 2;
    doc.image(bytes, x, cursor, finalW, finalH);
    return cursor + finalH + 4;
  }

  /* ── history table ─────────────────────────────────────────────────── */

  const COLUMNS = [
    { title: "#",       x: MARGIN,        width: 24,  align: "left" },
    { title: "Date",    x: MARGIN + 28,   width: 116, align: "left" },
    { title: "Site",    x: MARGIN + 148,  width: 112, align: "left" },
    { title: "Method",  x: MARGIN + 264,  width: 74,  align: "left" },
    { title: "Reading", x: MARGIN + 342,  width: 92,  align: "right" },
    { title: "GPM",     x: MARGIN + 438,  width: 46,  align: "right" },
    { title: "GPH",     x: MARGIN + 488,  width: 0,   align: "right" },
  ];

  function drawColumnHeader(doc, y) {
    doc.rect(MARGIN, y, CONTENT_WIDTH, 18, { fill: HEADER_FILL });
    COLUMNS.forEach(function (col) {
      const w = col.width > 0 ? col.width : CONTENT_RIGHT - col.x;
      doc.text(col.title, col.x, y + 4, { size: 9, bold: true, align: col.align, width: w });
    });
    return y + 20;
  }

  function truncate(doc, str, size, maxWidth) {
    if (doc.measure(str, size) <= maxWidth) return str;
    let out = str;
    while (out.length > 1 && doc.measure(out + "…", size) > maxWidth) out = out.slice(0, -1);
    return out + "…";
  }

  function rowValues(rec, index) {
    const core = FR.core, fmt = FR.format;
    let method, reading;
    if (rec.mode === core.MODES.weir.id) {
      const t = FR.weir.typeFor(rec.weirType);
      method = "Weir " + t.shortLabel;
      reading = fmt.formatVolume(rec.headInches) + " in head";
    } else if (rec.mode === core.MODES.manualEntry.id) {
      method = "Manual";
      reading = "—";
    } else {
      const unit = core.unitFor(rec.volumeUnit);
      method = "Timed";
      reading = fmt.formatVolume(rec.volume) + " " + unit.inputSuffix +
        " / " + fmt.formatElapsed(rec.elapsedSeconds);
    }
    return [
      String(index),
      fmt.formatTimestampShort(rec.timestamp),
      rec.siteLabel || "—",
      method,
      reading,
      fmt.formatFlow(rec.gpm),
      fmt.formatFlow(rec.gph),
    ];
  }

  function buildHistoryPDF(records) {
    const doc = FR.pdf.createDocument();
    const sorted = (records || []).slice().sort(function (a, b) {
      return new Date(b.timestamp) - new Date(a.timestamp);
    });
    const generated = "Generated " + FR.format.formatTimestampMedium(new Date());

    doc.addPage();
    let y = MARGIN;
    y = drawHeader(doc, "FloRun History — " + sorted.length +
      (sorted.length === 1 ? " Measurement" : " Measurements"), generated, y);
    y = drawRule(doc, y) + 8;
    y = drawColumnHeader(doc, y);

    const rowHeight = 18;
    for (let i = 0; i < sorted.length; i++) {
      if (y + rowHeight > BOTTOM_LIMIT) {
        drawFooter(doc);
        doc.addPage();
        y = MARGIN;
        y = drawHeader(doc, "FloRun History (continued)", generated, y);
        y = drawRule(doc, y) + 8;
        y = drawColumnHeader(doc, y);
      }
      if (i % 2 === 0) doc.rect(MARGIN, y, CONTENT_WIDTH, rowHeight, { fill: STRIPE });
      const values = rowValues(sorted[i], i + 1);
      for (let c = 0; c < COLUMNS.length; c++) {
        const col = COLUMNS[c];
        const w = col.width > 0 ? col.width : CONTENT_RIGHT - col.x;
        doc.text(truncate(doc, values[c], 9, w), col.x, y + 4,
          { size: 9, align: col.align, width: w });
      }
      y += rowHeight;
    }

    if (!sorted.length) {
      doc.text("No measurements saved.", MARGIN, y + 10, { size: 11, color: GRAY });
    }

    drawFooter(doc);
    return doc.build();
  }

  /* ── delivery ──────────────────────────────────────────────────────── */

  /*
   * Hand a generated file to the user. An <a download> click is the only
   * approach that works across desktop and iOS Safari without a popup, and it
   * needs no CSP relaxation. The object URL is revoked on the next tick --
   * immediately would race the download on some browsers.
   */
  function download(bytes, filename, mime) {
    const blob = bytes instanceof Blob ? bytes : new Blob([bytes], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = root.document.createElement("a");
    a.href = url;
    a.download = filename;
    a.rel = "noopener";
    a.style.display = "none";
    root.document.body.appendChild(a);
    a.click();
    setTimeout(function () {
      try { root.document.body.removeChild(a); } catch (e) {}
      URL.revokeObjectURL(url);
    }, 2000);
    return url;
  }

  function exportSingle(rec) {
    const stamp = FR.format.fileStamp(rec.timestamp);
    const promise = rec.photoId ? FR.photos.bytesFor(rec.photoId) : Promise.resolve(null);
    return promise.catch(function () { return null; }).then(function (photoBytes) {
      const bytes = buildSinglePDF(rec, photoBytes);
      download(bytes, "FloRun-" + stamp + ".pdf", "application/pdf");
      return bytes.length;
    });
  }

  function exportHistoryPDF(records) {
    const bytes = buildHistoryPDF(records);
    download(bytes, "FloRun-History-" + FR.format.fileStamp(new Date()) + ".pdf", "application/pdf");
    return Promise.resolve(bytes.length);
  }

  function exportHistoryCSV(records) {
    const text = FR.csv.build(records);
    download(new Blob([text], { type: "text/csv;charset=utf-8" }),
      "FloRun-History-" + FR.format.fileStamp(new Date()) + ".csv", "text/csv");
    return Promise.resolve(text.length);
  }

  FR.exporter = {
    APP_VERSION,
    buildSinglePDF, buildHistoryPDF,
    exportSingle, exportHistoryPDF, exportHistoryCSV,
    download,
    _rowValues: rowValues,
  };
})(typeof self !== "undefined" ? self : this);
